export const GET_ALL_SOSREQUESTS_START = 'sosrequests/GET_ALL_SOSREQUESTS_START';
export const GET_ALL_SOSREQUESTS_SUCCESS = 'sosrequests/GET_ALL_SOSREQUESTS_SUCCESS';
export const GET_ALL_SOSREQUESTS_FAILED = 'sosrequests/GET_ALL_SOSREQUESTS_FAILED';
export const CREATE_SOSREQUEST_START = 'sosrequests/CREATE_SOSREQUEST_START';
export const CREATE_SOSREQUEST_SUCCESS = 'sosrequests/CREATE_SOSREQUEST_SUCCESS';
export const CREATE_SOSREQUEST_FAILED = 'sosrequests/CREATE_SOSREQUEST_FAILED';
export const UPDATE_SOSREQUEST_START = 'sosrequests/UPDATE_SOSREQUEST_START';
export const UPDATE_SOSREQUEST_SUCCESS = 'sosrequests/UPDATE_SOSREQUEST_SUCCESS';
export const UPDATE_SOSREQUEST_FAILED = 'sosrequests/UPDATE_SOSREQUEST_FAILED';
export const DELETE_SOSREQUEST_START = 'sosrequests/DELETE_SOSREQUEST_START';
export const DELETE_SOSREQUEST_SUCCESS = 'sosrequests/DELETE_SOSREQUEST_SUCCESS';
export const DELETE_SOSREQUEST_FAILED = 'sosrequests/DELETE_SOSREQUEST_FAILED';

