export const GET_COORDS_START = 'app/GET_COORDS_START';
export const GET_COORDS_SUCCESS = 'app/GET_COORDS_SUCCESS';
export const GET_COORDS_FAILED = 'app/GET_COORDS_FAILED';

export const SHOW_COMMUNITY_LIST = 'app/SHOW_COMMUNITY_LIST';
export const HIDE_COMMUNITY_LIST = 'app/HIDE_COMMUNITY_LIST';

//auth
export const SIGNUP_EMAIL_START = 'app/SIGNUP_EMAIL_START';
export const SIGNUP_EMAIL_SUCCESS = 'app/SIGNUP_EMAIL_SUCCESS';
export const SIGNUP_EMAIL_FAILED = 'app/SIGNUP_EMAIL_FAILED';

export const LOGIN_START = 'app/LOGIN_START';
export const LOGIN_SUCCESS = 'app/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'app/LOGIN_FAILED';

export const LOGOUT = 'app/LOGOUT';

/* Facebook, Google, Twitter will go here 

*/

//User Settings
export const EDIT_START = 'app/EDIT_START';
export const EDIT_END = 'app/EDIT_END';

export const MEDICAL_SETTINGS_GET_START = 'app/MEDICAL_SETTINGS_GET_START';
export const MEDICAL_SETTINGS_GET_SUCCESS = 'app/MEDICAL_SETTINGS_GET_SUCCESS';
export const MEDICAL_SETTINGS_GET_FAILED = 'app/MEDICAL_SETTINGS_GET_FAILED';

export const MEDICAL_SETTINGS_PATCH_START = 'app/MEDICAL_SETTINGS_PATCH_START';
export const MEDICAL_SETTINGS_PATCH_SUCCESS = 'app/MEDICAL_SETTINGS_PATCH_SUCCESS';
export const MEDICAL_SETTINGS_PATCH_FAILED = 'app/MEDICAL_SETTINGS_PATCH_FAILED';

export const PERSONAL_SETTINGS_GET_START = 'app/PERSONAL_SETTINGS_GET_START';
export const PERSONAL_SETTINGS_GET_SUCCESS = 'app/PERSONAL_SETTINGS_GET_SUCCESS';
export const PERSONAL_SETTINGS_GET_FAILED = 'app/PERSONAL_SETTINGS_GET_FAILED';

export const PERSONAL_SETTINGS_PATCH_START = 'app/PERSONAL_SETTINGS_PATCH_START';
export const PERSONAL_SETTINGS_PATCH_SUCCESS = 'app/PERSONAL_SETTINGS_PATCH_SUCCESS';
export const PERSONAL_SETTINGS_PATCH_FAILED = 'app/PERSONAL_SETTINGS_PATCH_FAILED';
