export const GET_COORDS_START = 'app/GET_COORDS_START';
export const GET_COORDS_SUCCESS = 'app/GET_COORDS_SUCCESS';
export const GET_COORDS_FAILED = 'app/GET_COORDS_FAILED';

export const SHOW_COMMUNITY_LIST = 'app/SHOW_COMMUNITY_LIST';
export const HIDE_COMMUNITY_LIST = 'app/HIDE_COMMUNITY_LIST';

