export const GET_ALL_INCIDENTS_START = 'incidents/GET_ALL_INCIDENTS_START';
export const GET_ALL_INCIDENTS_SUCCESS = 'incidents/GET_ALL_INCIDENTS_SUCCESS';
export const GET_ALL_INCIDENTS_FAILED = 'incidents/GET_ALL_INCIDENTS_FAILED';
export const CREATE_INCIDENT_START = 'incidents/CREATE_INCIDENT_START';
export const CREATE_INCIDENT_SUCCESS = 'incidents/CREATE_INCIDENT_SUCCESS';
export const CREATE_INCIDENT_FAILED = 'incidents/CREATE_INCIDENT_FAILED';
export const UPDATE_INCIDENT_START = 'incidents/UPDATE_INCIDENT_START';
export const UPDATE_INCIDENT_SUCCESS = 'incidents/UPDATE_INCIDENT_SUCCESS';
export const UPDATE_INCIDENT_FAILED = 'incidents/UPDATE_INCIDENT_FAILED';
export const DELETE_INCIDENT_START = 'incidents/DELETE_INCIDENT_START';
export const DELETE_INCIDENT_SUCCESS = 'incidents/DELETE_INCIDENT_SUCCESS';
export const DELETE_INCIDENT_FAILED = 'incidents/DELETE_INCIDENT_FAILED';

